version: '2'

services:
  bind:
    restart: always
    image: 192.168.3.200:80/library/sameersbn/bind
    container_name: bind
    environment:
    - "ROOT_PASSWORD:root"
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    - "10000:10000/tcp"
    volumes:
    - /home/docker/bind/data:/data